name: PR
on: 
  - pull_request
  - push
jobs:
  build-and-run-tests:
    name: Build & run tests
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Build
      run: go build ./...
    - name: Run go vet
      run: go vet ./...
    - name: Run go tests
      run: go test -v ./...
